// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Echomong defines model for Echomong.
type Echomong struct {
	Id     *int64 `json:"id,omitempty"`
	ImgUrl string `json:"img_url"`
	Lyrics string `json:"lyrics"`
	Title  string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Marker defines model for Marker.
type Marker struct {
	EchomongId int64   `json:"echomong_id"`
	Id         *int64  `json:"id,omitempty"`
	Latitude   float32 `json:"latitude"`
	Longitude  float32 `json:"longitude"`
}

// NewEchomong defines model for NewEchomong.
type NewEchomong struct {
	ImgUrl string `json:"img_url"`
	Lyrics string `json:"lyrics"`
	Title  string `json:"title"`
}

// NewMarker defines model for NewMarker.
type NewMarker struct {
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// CreateEchomongJSONRequestBody defines body for CreateEchomong for application/json ContentType.
type CreateEchomongJSONRequestBody = NewEchomong

// AddMarkerToEchomongJSONRequestBody defines body for AddMarkerToEchomong for application/json ContentType.
type AddMarkerToEchomongJSONRequestBody = NewMarker

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 모든 에코몽 목록 조회
	// (GET /echomongs)
	GetEchomongs(w http.ResponseWriter, r *http.Request)
	// 새 에코몽 생성
	// (POST /echomongs)
	CreateEchomong(w http.ResponseWriter, r *http.Request)
	// ID로 특정 에코몽 조회
	// (GET /echomongs/{echomongId})
	GetEchomongById(w http.ResponseWriter, r *http.Request, echomongId int64)
	// 특정 에코몽의 모든 마커 조회
	// (GET /echomongs/{echomongId}/markers)
	GetMarkersForEchomong(w http.ResponseWriter, r *http.Request, echomongId int64)
	// 특정 에코몽에 새 마커 추가
	// (POST /echomongs/{echomongId}/markers)
	AddMarkerToEchomong(w http.ResponseWriter, r *http.Request, echomongId int64)
	// (지도용) 모든 마커 목록 조회
	// (GET /markers)
	GetAllMarkers(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// 모든 에코몽 목록 조회
// (GET /echomongs)
func (_ Unimplemented) GetEchomongs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 새 에코몽 생성
// (POST /echomongs)
func (_ Unimplemented) CreateEchomong(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ID로 특정 에코몽 조회
// (GET /echomongs/{echomongId})
func (_ Unimplemented) GetEchomongById(w http.ResponseWriter, r *http.Request, echomongId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 특정 에코몽의 모든 마커 조회
// (GET /echomongs/{echomongId}/markers)
func (_ Unimplemented) GetMarkersForEchomong(w http.ResponseWriter, r *http.Request, echomongId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 특정 에코몽에 새 마커 추가
// (POST /echomongs/{echomongId}/markers)
func (_ Unimplemented) AddMarkerToEchomong(w http.ResponseWriter, r *http.Request, echomongId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (지도용) 모든 마커 목록 조회
// (GET /markers)
func (_ Unimplemented) GetAllMarkers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEchomongs operation middleware
func (siw *ServerInterfaceWrapper) GetEchomongs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEchomongs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEchomong operation middleware
func (siw *ServerInterfaceWrapper) CreateEchomong(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEchomong(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEchomongById operation middleware
func (siw *ServerInterfaceWrapper) GetEchomongById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "echomongId" -------------
	var echomongId int64

	err = runtime.BindStyledParameterWithOptions("simple", "echomongId", chi.URLParam(r, "echomongId"), &echomongId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "echomongId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEchomongById(w, r, echomongId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMarkersForEchomong operation middleware
func (siw *ServerInterfaceWrapper) GetMarkersForEchomong(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "echomongId" -------------
	var echomongId int64

	err = runtime.BindStyledParameterWithOptions("simple", "echomongId", chi.URLParam(r, "echomongId"), &echomongId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "echomongId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMarkersForEchomong(w, r, echomongId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddMarkerToEchomong operation middleware
func (siw *ServerInterfaceWrapper) AddMarkerToEchomong(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "echomongId" -------------
	var echomongId int64

	err = runtime.BindStyledParameterWithOptions("simple", "echomongId", chi.URLParam(r, "echomongId"), &echomongId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "echomongId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddMarkerToEchomong(w, r, echomongId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllMarkers operation middleware
func (siw *ServerInterfaceWrapper) GetAllMarkers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllMarkers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echomongs", wrapper.GetEchomongs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/echomongs", wrapper.CreateEchomong)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echomongs/{echomongId}", wrapper.GetEchomongById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/echomongs/{echomongId}/markers", wrapper.GetMarkersForEchomong)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/echomongs/{echomongId}/markers", wrapper.AddMarkerToEchomong)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/markers", wrapper.GetAllMarkers)
	})

	return r
}
