services:
  # 1. 'app' 서비스 (프론트엔드 / 계산대)
  app:
    build:
      context: ../frontend
      dockerfile: ../backend/Dockerfile_frontend.dockerfile
      args:
        VITE_KAKAO_MAP_REST_KEY: ${VITE_KAKAO_MAP_REST_KEY}
        VITE_KAKAO_MAP_JS_KEY: ${VITE_KAKAO_MAP_JS_KEY}
    container_name: ecomong_app
    ports:
      - "8080:80"
    depends_on:
      - db
      - backend # <-- ★★★ 백엔드가 실행된 후에 프론트가 켜지도록 추가 ★★★

  # 2. 'db' 서비스 (데이터베이스 / 창고)
  db:
    image: postgres:15-alpine
    container_name: ecomong_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # ▼▼▼ 3. 'backend' 서비스 (백엔드 API / 주방) - 이 부분을 추가! ▼▼▼
  backend:
    build:
      context: . # 1. 재료(소스)는 현재 backend 폴더를 사용
      dockerfile: Dockerfile_backend.dockerfile # 2. '주방' 전용 설계도
    container_name: ecomong_backend
    restart: always
    ports:
      - "8000:8000" # 3. 내 Mac 8000 포트를 '주방' 8000 포트에 연결
    env_file:
      - ./.env # 4. '주방'이 DB 접속 정보를 위해 .env 파일을 읽도록 설정
    depends_on:
      - db # 5. '창고'(db)가 먼저 준비된 후에 '주방'이 켜지도록 설정

volumes:
  db_data:
