// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Echomong defines model for Echomong.
type Echomong struct {
	Id     *int    `json:"id,omitempty"`
	ImgUrl *string `json:"img_url,omitempty"`
	Lyrics *string `json:"lyrics,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code 에러 코드 (optional)
	Code *int `json:"code,omitempty"`

	// Error 에러 메시지
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string `json:"token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
}

// JoinTeamJSONBody defines parameters for JoinTeam.
type JoinTeamJSONBody struct {
	Title string `json:"title"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// JoinTeamJSONRequestBody defines body for JoinTeam for application/json ContentType.
type JoinTeamJSONRequestBody JoinTeamJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Echomong 1개 조회
	// (GET /echomong/{id})
	GetEchomong(c *gin.Context, id int)
	// 로그인
	// (POST /login)
	LoginUser(c *gin.Context)
	// 회원가입
	// (POST /register)
	RegisterUser(c *gin.Context)
	// 팀 이름으로 팀 가입하기
	// (POST /user/team)
	JoinTeam(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetEchomong operation middleware
func (siw *ServerInterfaceWrapper) GetEchomong(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEchomong(c, id)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginUser(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterUser(c)
}

// JoinTeam operation middleware
func (siw *ServerInterfaceWrapper) JoinTeam(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.JoinTeam(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/echomong/:id", wrapper.GetEchomong)
	router.POST(options.BaseURL+"/login", wrapper.LoginUser)
	router.POST(options.BaseURL+"/register", wrapper.RegisterUser)
	router.POST(options.BaseURL+"/user/team", wrapper.JoinTeam)
}

type GetEchomongRequestObject struct {
	Id int `json:"id"`
}

type GetEchomongResponseObject interface {
	VisitGetEchomongResponse(w http.ResponseWriter) error
}

type GetEchomong200JSONResponse Echomong

func (response GetEchomong200JSONResponse) VisitGetEchomongResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEchomong404JSONResponse ErrorResponse

func (response GetEchomong404JSONResponse) VisitGetEchomongResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse LoginResponse

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse ErrorResponse

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser500JSONResponse ErrorResponse

func (response LoginUser500JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse User

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse ErrorResponse

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse ErrorResponse

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser500JSONResponse ErrorResponse

func (response RegisterUser500JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type JoinTeamRequestObject struct {
	Body *JoinTeamJSONRequestBody
}

type JoinTeamResponseObject interface {
	VisitJoinTeamResponse(w http.ResponseWriter) error
}

type JoinTeam200JSONResponse struct {
	Message *string `json:"message,omitempty"`
	TeamId  *int    `json:"team_id,omitempty"`
}

func (response JoinTeam200JSONResponse) VisitJoinTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinTeam404JSONResponse ErrorResponse

func (response JoinTeam404JSONResponse) VisitJoinTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type JoinTeam500JSONResponse ErrorResponse

func (response JoinTeam500JSONResponse) VisitJoinTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Echomong 1개 조회
	// (GET /echomong/{id})
	GetEchomong(ctx context.Context, request GetEchomongRequestObject) (GetEchomongResponseObject, error)
	// 로그인
	// (POST /login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// 회원가입
	// (POST /register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// 팀 이름으로 팀 가입하기
	// (POST /user/team)
	JoinTeam(ctx context.Context, request JoinTeamRequestObject) (JoinTeamResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetEchomong operation middleware
func (sh *strictHandler) GetEchomong(ctx *gin.Context, id int) {
	var request GetEchomongRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEchomong(ctx, request.(GetEchomongRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEchomong")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetEchomongResponseObject); ok {
		if err := validResponse.VisitGetEchomongResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx *gin.Context) {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx *gin.Context) {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx, request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		if err := validResponse.VisitRegisterUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinTeam operation middleware
func (sh *strictHandler) JoinTeam(ctx *gin.Context) {
	var request JoinTeamRequestObject

	var body JoinTeamJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.JoinTeam(ctx, request.(JoinTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(JoinTeamResponseObject); ok {
		if err := validResponse.VisitJoinTeamResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXUW8bRRD+K6uFh1ayYocUJO6tlQpq1QcUiniIoup6nly2+Havu3sgyzrJFLcC4gcj",
	"UtUK50CkUGhVJLdNwYjCD/Lt/Qe0u47ts8+kgJv2xTrfzs588803s3sN7LEgZBSoFNhpYOFtQ+Cax4ve",
	"NgsY9fVzyFkIXBIwK6Sqf2U9BOxgQiX4wHFcwiTwr0W8phe3GA9ciR0ccYJLx7ZCckJ9bVqrc+KJKTeT",
	"JUlkDQpW4rEbdv0GeFLbXuSc8XUQIaMC5oF6rGreVkF4nISSMIodrO510u8fIfXnbvptgs4w896tnZ3g",
	"nMoJdISFPtIHu2onUT8153OMS5jDzYhwqGJnY+RnsyCHK8wndB1uRiDkfAoQuKRWyFPoCvEZ49ViqnKx",
	"jY+pHf8AYxGVkn0C9ORQ1qzI/zr4REjg/zPTgNArQH25jZ13CnQVCeDUDWDGdK30ghSN95/A1kcC+L9J",
	"YRrXibqOS1iAF3Ei6x/qfrTOL4DLgZ+PdD4NfN38e++4zS5/fBWXbPdqT3Z1IsptKUMca8eEbjEDwnbZ",
	"uMvR+Q8u4RL+FLiwCl9dqaxUNHQWAnVDgh28tlJZWTPMyG0DqQyj3eUGqcb6jQ+mspoUV7fKpSp28Psg",
	"x8NE7+ZuABK4wM5GAxMdTHvEJWwZ0vNlujqSRzDKzS0aPPGmtrbCNbDeqlRs91MJ1OBxw7BGPIOofEMw",
	"Ohl1+ulNDlvYwW+UJ7OwPBqE5TFww97MEGg9Hj59pjk6Vzm3vIi5mVYUtv+X6rWQ+rKL1L07qtfOKcaQ",
	"Oq2VjU1NkIiCwOX16YqvDvsJUgf9bM96KNf0CDCqZqKgjGZCGOHb6oCQF1i1vrTEc4Mwzneo1kD8Esuc",
	"n34FpKcHyfC3geoNkK06OpPd+SH7vI/SfjIcfHXWqmD1FFXQG6j7PaR2DrP2zzr628tU/YnRW0n6pIXS",
	"W0fpr02kuofpj10rw7HOxoxZcfHR/F+sr+MT4iVKbPYQeiGVLa+oJrMiNr/oqdZjND1PTrOW+9304R9p",
	"J0Fqb1c9+cUCePcUARx+kz59ZgD0jvSVqvccpd1O+vUuUrceqb0Har+TPrz9Ooo822ur7zrDflPt37Y6",
	"1yd9WYIbLBb6ZUboVW3x30U+czlbfGXOXc6M2fx1ZvmjNg8vACFcH4pv++AG14o/KOJCoPkSZe0msuyj",
	"V3QaZ3eP0p3fUdZumkN5/mx+NaK1Hyizam03TYvdb6nkeXqQoAl92d3ucNDXDuO/AwAA//9uT2hnFA4A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
