/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as IndexRouteImport } from './routes/index'

const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/home': typeof HomeRoute
  '/quiz': typeof QuizRoute
  '/reward': typeof RewardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/home': typeof HomeRoute
  '/quiz': typeof QuizRoute
  '/reward': typeof RewardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/home': typeof HomeRoute
  '/quiz': typeof QuizRoute
  '/reward': typeof RewardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/booth' | '/home' | '/quiz' | '/reward'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/booth' | '/home' | '/quiz' | '/reward'
  id: '__root__' | '/' | '/booth' | '/home' | '/quiz' | '/reward'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoothRoute: typeof BoothRoute
  HomeRoute: typeof HomeRoute
  QuizRoute: typeof QuizRoute
  RewardRoute: typeof RewardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoothRoute: BoothRoute,
  HomeRoute: HomeRoute,
  QuizRoute: QuizRoute,
  RewardRoute: RewardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
