// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: echomong.sql

package db

import (
	"context"
)

const getEchomong = `-- name: GetEchomong :one
SELECT id, title, lyrics, img_url FROM echomong
WHERE id = $1 LIMIT 1
`

// db/query/echomong.sql
func (q *Queries) GetEchomong(ctx context.Context, id int64) (Echomong, error) {
	row := q.db.QueryRow(ctx, getEchomong, id)
	var i Echomong
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lyrics,
		&i.ImgUrl,
	)
	return i, err
}

const getEchomongs = `-- name: GetEchomongs :many
SELECT id, title, lyrics, img_url FROM echomong
ORDER BY id
`

func (q *Queries) GetEchomongs(ctx context.Context) ([]Echomong, error) {
	rows, err := q.db.Query(ctx, getEchomongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Echomong
	for rows.Next() {
		var i Echomong
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Lyrics,
			&i.ImgUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
