// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: echomong.sql

package db

import (
	"context"
)

const getEchomong = `-- name: GetEchomong :one
SELECT id, title, lyrics, img_url FROM echomong
WHERE id = $1 LIMIT 1
`

// db/query/echomong.sql
func (q *Queries) GetEchomong(ctx context.Context, id int64) (Echomong, error) {
	row := q.db.QueryRow(ctx, getEchomong, id)
	var i Echomong
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lyrics,
		&i.ImgUrl,
	)
	return i, err
}
