// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Echomong struct {
	ID     int64       `json:"id"`
	Title  pgtype.Text `json:"title"`
	Lyrics pgtype.Text `json:"lyrics"`
	ImgUrl pgtype.Text `json:"img_url"`
}

type Marker struct {
	ID         int64   `json:"id"`
	Latitude   float64 `json:"latitude"`
	Longitude  float64 `json:"longitude"`
	EchomongID int64   `json:"echomong_id"`
}

type User struct {
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Team         pgtype.Int8        `json:"team"`
}
