// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, username, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING email, username, password_hash, created_at, team
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Team,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT email, username, password_hash, created_at, team FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Team,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT email, username, password_hash, created_at, team FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.Team,
	)
	return i, err
}

const updateUserTeam = `-- name: UpdateUserTeam :exec
UPDATE users
SET team = $1
WHERE email = $2
`

type UpdateUserTeamParams struct {
	Team  pgtype.Int8 `json:"team"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserTeam(ctx context.Context, arg UpdateUserTeamParams) error {
	_, err := q.db.Exec(ctx, updateUserTeam, arg.Team, arg.Email)
	return err
}
